// Generated by `sqlfu generate`. Do not edit.
// Row types for every table and view in your project's schema.

export type SessionRecoveryRow = {
	session_id: string;
	recovery_command: string;
	created_at_ms: number;
};

export type SessionsRow = {
	id: string;
	cwd: string;
	launch_command: string;
	created_at_ms: number;
	archived_at_ms: number | null;
};
